

import { Injectable, signal, computed, effect } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  private translations: { [key: string]: { [key: string]: string } } = {
    ar: {
      'Quran Kareem': 'القرآن الكريم',
      'Home': 'الرئيسية',
      'Surahs': 'السور',
      'Reciters': 'القراء',
      'Radio': 'الإذاعة',
      'Language': 'اللغة',
      'Listen to Holy Quran Radio': 'استمع إلى إذاعة القرآن الكريم',
      'Explore the Holy Quran': 'تصفح القرآن الكريم',
      'Choose from renowned reciters': 'اختر من بين مشاهير القراء',
      'Listen to Live Radio': 'استمع للبث المباشر',
      'All Surahs': 'كل السور',
      'All Reciters': 'كل القراء',
      'All Radio Stations': 'جميع محطات الإذاعة',
      'Revelation': 'النزول',
      'Ayahs': 'آيات',
      'Meccan': 'مكية',
      'Medinan': 'مدنية',
      'Recitations': 'التلاوات',
      'Select Reciter': 'اختر القارئ',
      'Loading...': 'جاري التحميل...',
      'Error loading data.': 'خطأ في تحميل البيانات.',
      'Tafsir': 'التفسير',
      'Select Tafsir': 'اختر التفسير',
      'Show Tafsir': 'إظهار التفسير',
      'Hide Tafsir': 'إخفاء التفسير',
      'Ask AI': 'اسأل الذكاء الاصطناعي',
      'AI Explanation': 'شرح بالذكاء الاصطناعي',
      'Generating explanation...': 'جاري إنشاء الشرح...',
      'Could not get explanation.': 'تعذر الحصول على شرح.',
      'Close': 'إغلاق',
      'Favorites': 'المفضلة',
      'My Favorites': 'مفضلتي',
      'Favorited Surahs': 'السور المفضلة',
      'Favorited Ayahs': 'الآيات المفضلة',
      'No favorites yet.': 'لا يوجد مفضلات بعد.',
      'Add to favorites': 'إضافة إلى المفضلة',
      'Remove from favorites': 'إزالة من المفضلة',
      'Add to bookmarks': 'إضافة إلى الإشارات المرجعية',
      'Remove from bookmarks': 'إزالة من الإشارات المرجعية',
      'Qibla': 'القبلة',
      'Find the direction to the Kaaba': 'ابحث عن اتجاه الكعبة المشرفة',
      'Get Location': 'الحصول على الموقع',
      'Qibla Direction': 'اتجاه القبلة',
      'Distance': 'المسافة',
      'Acquiring location...': 'جاري تحديد الموقع...',
      'Location acquired.': 'تم تحديد الموقع.',
      'Could not get location. Please enable location services.': 'تعذر الحصول على الموقع. يرجى تفعيل خدمات الموقع.',
      'Compass not supported.': 'البوصلة غير مدعومة.',
      'km': 'كم',
      'Calibrate Compass': 'معايرة البوصلة',
      'For best results, move your phone in a figure-eight pattern to calibrate the compass.': 'للحصول على أفضل النتائج، قم بتحريك هاتفك على شكل رقم ثمانية لمعايرة البوصلة.',
      'Done': 'تم',
      'Prayer Times': 'أوقات الصلاة',
      'Daily prayer times for your location': 'أوقات الصلاة اليومية لموقعك',
      'Fajr': 'الفجر',
      'Sunrise': 'الشروق',
      'Dhuhr': 'الظهر',
      'Asr': 'العصر',
      'Maghrib': 'المغرب',
      'Isha': 'العشاء',
      'Next prayer': 'الصلاة التالية',
      'Refresh': 'تحديث',
      'Today': 'اليوم',
      'Location': 'الموقع',
      'Error loading prayer times.': 'خطأ في تحميل أوقات الصلاة.',
      'Search Reciters...': 'ابحث عن قارئ...',
      'Playback Mode': 'وضع التشغيل',
      'By Ayah': 'آية بآية',
      'Full Surah': 'سورة كاملة',
      'Play Surah': 'تشغيل السورة',
      'All Surahs by': 'جميع سور القارئ',
      'Listen': 'استماع',
      'Not available': 'غير متاح',
      'No reciters found.': 'لم يتم العثور على قراء.',
      'Translation View': 'عرض الترجمة',
      'Arabic': 'عربي',
      'English': 'إنجليزي',
      'Sort by': 'فرز حسب',
      'Surah Number': 'رقم السورة',
      'Name': 'الاسم',
      'Date Added': 'تاريخ الإضافة',
      'Ayah Number': 'رقم الآية',
      'Jump to Ayah': 'الانتقال إلى آية',
      'Go': 'اذهب',
      'Search favorites...': 'ابحث في المفضلة...',
      'No favorites found matching your search.': 'لم يتم العثور على مفضلات مطابقة لبحثك.',
      'Verse of the Day': 'آية اليوم',
      'Welcome to Quran Kareem': 'أهلاً بك في القرآن الكريم',
      'Your daily inspiration from the Holy Quran': 'إلهامك اليومي من القرآن الكريم',
      'Explore all 114 chapters': 'تصفح جميع السور الـ 114',
      'Listen to various recitations': 'استمع إلى تلاوات متنوعة',
      'Tune in to live Quran broadcasts': 'استمع إلى بث مباشر للقرآن',
      'Find the direction of the Kaaba': 'ابحث عن اتجاه الكعبة المشرفة',
      'Check daily prayer timings': 'تحقق من أوقات الصلاة اليومية',
      'Essential Tools': 'الأدوات الأساسية',
      'Surah Information': 'معلومات السورة',
      'Revelation Place': 'مكان النزول',
      'Number of Verses': 'عدد الآيات',
      'Translated Name': 'الاسم المترجم',
      'Bookmarks': 'الإشارات المرجعية',
      'My Bookmarks': 'إشاراتي المرجعية',
      'Bookmarked Ayahs': 'الآيات المرجعية',
      'No bookmarks yet.': 'لا يوجد إشارات مرجعية بعد.',
      'Search bookmarks...': 'ابحث في الإشارات المرجعية...',
      'No bookmarks found matching your search.': 'لم يتم العثور على إشارات مرجعية مطابقة لبحثك.',
      'You can add ayahs to your bookmarks by clicking the bookmark icon on any surah page.': 'يمكنك إضافة الآيات إلى إشاراتك المرجعية عن طريق النقر على أيقونة الإشارة المرجعية في صفحة أي سورة.',
      'Explore Surahs': 'تصفح السور',
      'Share Ayah': 'مشاركة الآية',
      'An Ayah from the Quran': 'آية من القرآن الكريم',
      'Copied to clipboard!': 'تم النسخ إلى الحافظة!',
      'Could not copy.': 'تعذر النسخ.',
      'Compass unstable.': 'البوصلة غير مستقرة.',
      'For better accuracy, please recalibrate.': 'للحصول على دقة أفضل، يرجى إعادة المعايرة.',
      'Recalibrate': 'إعادة المعايرة',
      'Quality': 'الجودة',
      'All': 'الكل',
      'Frequently Read Surahs': 'السور الأكثر قراءة',
      'About': 'حول التطبيق',
      'about_page_subtitle': 'رفيقك الرقمي الشامل للقرآن الكريم',
      'about_section_title': 'مهمتنا',
      'about_section_p1': 'تطبيق القرآن الكريم مصمم ليكون أداة جميلة وسهلة الاستخدام للقراءة والاستماع والتفاعل مع القرآن الكريم. هدفنا هو توفير تجربة سلسة وغنية للمسلمين في جميع أنحاء العالم للاتصال بكلام الله.',
      'about_section_p2': 'سواء كنت ترغب في قراءة السور، أو الاستماع إلى القراء المفضلين لديك، أو استكشاف المعاني الأعمق للآيات، فإن هذا التطبيق يوفر مجموعة شاملة من الميزات لدعم رحلتك الروحية.',
      'Key Features': 'الميزات الرئيسية',
      'feature_0': 'قراءة واستماع لجميع السور الـ 114.',
      'feature_1': 'الاختيار من بين مجموعة واسعة من القراء المشهورين.',
      'feature_2': 'الاستماع إلى محطات إذاعة القرآن الكريم الحية من جميع أنحاء العالم.',
      'feature_3': 'الحصول على شروحات مدعومة بالذكاء الاصطناعي للآيات لتعميق فهمك.',
      'feature_4': 'العثور على اتجاه القبلة باستخدام بوصلتنا الدقيقة.',
      'feature_5': 'التحقق من أوقات الصلاة اليومية لموقعك.',
      'feature_6': 'حفظ السور والآيات المفضلة لديك للوصول السريع.',
      'feature_7': 'وضع إشارات مرجعية على الآيات للعودة إليها بسهولة لاحقًا.',
      'feature_8': 'واجهة جميلة وسهلة الاستخدام مع دعم متعدد اللغات (العربية والإنجليزية).',
      'Data Sources': 'مصادر البيانات',
      'data_sources_intro': 'يعتمد هذا التطبيق على العديد من واجهات برمجة التطبيقات العامة عالية الجودة لتوفير بيانات دقيقة وموثوقة. نحن ممتنون للمطورين الذين يقفون وراء هذه الخدمات:',
      'quran_com_desc': 'يستخدم لقوائم السور، ونصوص الآيات، والترجمات، ومعلومات التفسير.',
      'mp3quran_desc': 'يستخدم لتلاوات السور الكاملة وبيانات محطات الإذاعة الحية.',
      'everyayah_desc': 'يوفر الملفات الصوتية لميزة التلاوة آية بآية.',
      'aladhan_desc': 'يستخدم لجلب أوقات الصلاة اليومية بناءً على موقع المستخدم.',
      'gemini_desc': 'يدعم ميزة "اسأل الذكاء الاصطناعي" لشرح الآيات.',
      'Developed By': 'تم التطوير بواسطة',
      'developer_motto': 'صناعة تجارب رقمية هادفة.',
      'Translation': 'الترجمة',
      'Translation Source': 'مصدر الترجمة',
      'None': 'بدون',
      'Settings': 'الإعدادات',
      'Word by Word': 'كلمة بكلمة',
      'On': 'تشغيل',
      'Off': 'إيقاف',
      
      // قسم المزيد والخدمات الجديدة
      'More': 'المزيد',
      'Religious Services': 'الخدمات الدينية',
      'Useful Tools': 'أدوات مفيدة',
      'Information': 'المعلومات',
      
      // المسبحة الرقمية
      'Digital Tasbih': 'المسبحة الرقمية',
      'Tasbih': 'التسبيح',
      'Reset': 'إعادة تعيين',
      'Total Count': 'العدد الإجمالي',
      'Current Round': 'الجولة الحالية',
      'SubhanAllah': 'سبحان الله',
      'Alhamdulillah': 'الحمد لله',
      'Allahu Akbar': 'الله أكبر',
      'La hawla wa la quwwata illa billah': 'لا حول ولا قوة إلا بالله',
      'Astaghfirullah': 'أستغفر الله',
      'La ilaha illa Allah': 'لا إله إلا الله',
      'Current Count': 'العدد الحالي',
      'All Tasbihat': 'جميع التسبيحات',
      '33 per round': '33 في الجولة',
      'Choose Tasbih': 'اختر التسبيحة',
      'Tap to count': 'انقر للعد',
      'Reset Current': 'إعادة تعيين الحالي',
      'Reset All': 'إعادة تعيين الكل',
      'Spiritual Benefits': 'الفوائد الروحية',
      'Inner Peace and Tranquility': 'السكينة والطمأنينة الداخلية',
      'Spiritual Strength': 'القوة الروحية',
      'Mindfulness and Focus': 'اليقظة الذهنية والتركيز',
      'Divine Connection': 'الصلة الإلهية',
      'Tap the circle to count your dhikr. Each complete round consists of 33 repetitions.': 'انقر على الدائرة لعد الذكر. كل جولة كاملة تتكون من 33 تكرار.',
      
      // أذكار الصباح والمساء
      'Adhkar': 'الأذكار',
      'Morning Adhkar': 'أذكار الصباح',
      'Evening Adhkar': 'أذكار المساء',
      'Post-Prayer Adhkar': 'أذكار ما بعد الصلاة',
      'Sleeping Adhkar': 'أذكار النوم',
      'times': 'مرات',
      'Read': 'قراءة',
      'Completed': 'مكتمل',
      'Mark as Read': 'وضع علامة كمقروء',
      'Reset Category': 'إعادة تعيين الفئة',
      'Benefits of Regular Dhikr': 'فوائد الذكر المنتظم',
      'Heart Purification': 'تطهير القلب',
      'Divine Protection': 'الحماية الإلهية',
      'Increased Barakah': 'زيادة البركة',
      'Peace of Mind': 'راحة البال',
      'Spiritual Elevation': 'الرفعة الروحية',
      'Community Blessing': 'بركة الجماعة',
      'Read each dhikr the specified number of times. Click the Read button after completing each recitation.': 'اقرأ كل ذكر العدد المحدد من المرات. انقر على زر القراءة بعد إكمال كل تلاوة.',
      
      // أسماء الله الحسنى
      '99 Names of Allah': 'أسماء الله الحسنى',
      'Asma ul Husna': 'أسماء الله الحسنى',
      'The 99 Beautiful Names': 'الأسماء الحسنى التسعة والتسعون',
      'Allah Name': 'الاسم',
      'Meaning': 'المعنى',
      'Description': 'الوصف',
      'No names found matching your search.': 'لم يتم العثور على أسماء تطابق بحثك.',
      'Clear Search': 'محو البحث',
      'Benefits of Reciting Asma ul Husna': 'فوائد تلاوة أسماء الله الحسنى',
      'Strengthens Faith': 'يقوي الإيمان',
      'Brings Inner Peace': 'يجلب السكينة الداخلية',
      'Increases Knowledge': 'يزيد المعرفة',
      'Click on any name to learn more about its meaning and significance.': 'انقر على أي اسم لمعرفة المزيد عن معناه وأهميته.',
      'Play Audio': 'تشغيل الصوت',
      
      // الأحاديث
      'Hadith': 'الحديث',
      'Sahih Bukhari': 'صحيح البخاري',
      'Sahih Muslim': 'صحيح مسلم',
      'Sunan Abu Dawud': 'سنن أبي داود',
      'Jami at-Tirmidhi': 'جامع الترمذي',
      'Narrator': 'الراوي',
      'Reference': 'المرجع',
      
      // حاسبة الزكاة
      'Zakat Calculator': 'حاسبة الزكاة',
      'Calculate Zakat': 'حساب الزكاة',
      'Gold': 'الذهب',
      'Silver': 'الفضة',
      'Cash': 'النقد',
      'Savings': 'الادخار',
      'Investment': 'الاستثمار',
      'Amount': 'المبلغ',
      'Total Wealth': 'إجمالي الثروة',
      'Zakat Amount': 'مبلغ الزكاة',
      'Nisab Threshold': 'نصاب الزكاة',
      'Currency': 'العملة',
      
      // خطة ختم القرآن
      'Quran Reading Plan': 'خطة ختم القرآن',
      'Complete in': 'إنهاء في',
      '30 days': '30 يوم',
      '60 days': '60 يوم',
      '90 days': '90 يوم',
      'Custom': 'مخصص',
      'Start Date': 'تاريخ البداية',
      'End Date': 'تاريخ النهاية',
      'Daily Reading': 'القراءة اليومية',
      'Progress': 'التقدم',
      'Days Completed': 'الأيام المكتملة',
      'Days Remaining': 'الأيام المتبقية',
      
      // التقويم الهجري
      'Islamic Calendar': 'التقويم الهجري',
      'Hijri Date': 'التاريخ الهجري',
      'Gregorian Date': 'التاريخ الميلادي',
      'Current Month': 'الشهر الحالي',
      'Islamic Events': 'المناسبات الإسلامية',
      'Muharram': 'محرم',
      'Safar': 'صفر',
      'Rabi al-Awwal': 'ربيع الأول',
      'Rabi al-Thani': 'ربيع الثاني',
      'Jumada al-Awwal': 'جمادى الأولى',
      'Jumada al-Thani': 'جمادى الثانية',
      'Rajab': 'رجب',
      'Shaban': 'شعبان',
      'Ramadan': 'رمضان',
      'Shawwal': 'شوال',
      'Dhul Qadah': 'ذو القعدة',
      'Dhul Hijjah': 'ذو الحجة',
    },
    en: {
      'Quran Kareem': 'Quran Kareem',
      'Home': 'Home',
      'Surahs': 'Surahs',
      'Reciters': 'Reciters',
      'Radio': 'Radio',
      'Language': 'Language',
      'Listen to Holy Quran Radio': 'Listen to Holy Quran Radio',
      'Explore the Holy Quran': 'Explore the Holy Quran',
      'Choose from renowned reciters': 'Choose from renowned reciters',
      'Listen to Live Radio': 'Listen to Live Radio',
      'All Surahs': 'All Surahs',
      'All Reciters': 'All Reciters',
      'All Radio Stations': 'All Radio Stations',
      'Revelation': 'Revelation',
      'Ayahs': 'Ayahs',
      'Meccan': 'Meccan',
      'Medinan': 'Medinan',
      'Recitations': 'Recitations',
      'Select Reciter': 'Select Reciter',
      'Loading...': 'Loading...',
      'Error loading data.': 'Error loading data.',
      'Tafsir': 'Tafsir',
      'Select Tafsir': 'Select Tafsir',
      'Show Tafsir': 'Show Tafsir',
      'Hide Tafsir': 'Hide Tafsir',
      'Ask AI': 'Ask AI',
      'AI Explanation': 'AI Explanation',
      'Generating explanation...': 'Generating explanation...',
      'Could not get explanation.': 'Could not get explanation.',
      'Close': 'Close',
      'Favorites': 'Favorites',
      'My Favorites': 'My Favorites',
      'Favorited Surahs': 'Favorited Surahs',
      'Favorited Ayahs': 'Favorited Ayahs',
      'No favorites yet.': 'No favorites yet.',
      'Add to favorites': 'Add to favorites',
      'Remove from favorites': 'Remove from favorites',
      'Add to bookmarks': 'Add to bookmarks',
      'Remove from bookmarks': 'Remove from bookmarks',
      'Qibla': 'Qibla',
      'Find the direction to the Kaaba': 'Find the direction to the Kaaba',
      'Get Location': 'Get Location',
      'Qibla Direction': 'Qibla Direction',
      'Distance': 'Distance',
      'Acquiring location...': 'Acquiring location...',
      'Location acquired.': 'Location acquired.',
      'Could not get location. Please enable location services.': 'Could not get location. Please enable location services.',
      'Compass not supported.': 'Compass not supported.',
      'km': 'km',
      'Calibrate Compass': 'Calibrate Compass',
      'For best results, move your phone in a figure-eight pattern to calibrate the compass.': 'For best results, move your phone in a figure-eight pattern to calibrate the compass.',
      'Done': 'Done',
      'Prayer Times': 'Prayer Times',
      'Daily prayer times for your location': 'Daily prayer times for your location',
      'Fajr': 'Fajr',
      'Sunrise': 'Sunrise',
      'Dhuhr': 'Dhuhr',
      'Asr': 'Asr',
      'Maghrib': 'Maghrib',
      'Isha': 'Isha',
      'Next prayer': 'Next prayer',
      'Refresh': 'Refresh',
      'Today': 'Today',
      'Location': 'Location',
      'Error loading prayer times.': 'Error loading prayer times.',
      'Search Reciters...': 'Search Reciters...',
      'Playback Mode': 'Playback Mode',
      'By Ayah': 'By Ayah',
      'Full Surah': 'Full Surah',
      'Play Surah': 'Play Surah',
      'All Surahs by': 'All Surahs by',
      'Listen': 'Listen',
      'Not available': 'Not available',
      'No reciters found.': 'No reciters found.',
      'Translation View': 'Translation View',
      'Arabic': 'Arabic',
      'English': 'English',
      'Sort by': 'Sort by',
      'Surah Number': 'Surah Number',
      'Name': 'Name',
      'Date Added': 'Date Added',
      'Ayah Number': 'Ayah Number',
      'Jump to Ayah': 'Jump to Ayah',
      'Go': 'Go',
      'Search favorites...': 'Search favorites...',
      'No favorites found matching your search.': 'No favorites found matching your search.',
      'Verse of the Day': 'Verse of the Day',
      'Welcome to Quran Kareem': 'Welcome to Quran Kareem',
      'Your daily inspiration from the Holy Quran': 'Your daily inspiration from the Holy Quran',
      'Explore all 114 chapters': 'Explore all 114 chapters',
      'Listen to various recitations': 'Listen to various recitations',
      'Tune in to live Quran broadcasts': 'Tune in to live Quran broadcasts',
      'Find the direction of the Kaaba': 'Find the direction of the Kaaba',
      'Check daily prayer timings': 'Check daily prayer timings',
      'Essential Tools': 'Essential Tools',
      'Surah Information': 'Surah Information',
      'Revelation Place': 'Revelation Place',
      'Number of Verses': 'Number of Verses',
      'Translated Name': 'Translated Name',
      'Bookmarks': 'Bookmarks',
      'My Bookmarks': 'My Bookmarks',
      'Bookmarked Ayahs': 'Bookmarked Ayahs',
      'No bookmarks yet.': 'No bookmarks yet.',
      'Search bookmarks...': 'Search bookmarks...',
      'No bookmarks found matching your search.': 'No bookmarks found matching your search.',
      'You can add ayahs to your bookmarks by clicking the bookmark icon on any surah page.': 'You can add ayahs to your bookmarks by clicking the bookmark icon on any surah page.',
      'Explore Surahs': 'Explore Surahs',
      'Share Ayah': 'Share Ayah',
      'An Ayah from the Quran': 'An Ayah from the Quran',
      'Copied to clipboard!': 'Copied to clipboard!',
      'Could not copy.': 'Could not copy.',
      'Compass unstable.': 'Compass unstable.',
      'For better accuracy, please recalibrate.': 'For better accuracy, please recalibrate.',
      'Recalibrate': 'Recalibrate',
      'Quality': 'Quality',
      'All': 'All',
      'Frequently Read Surahs': 'Frequently Read Surahs',
      'About': 'About',
      'about_page_subtitle': 'Your comprehensive digital companion for the Holy Quran.',
      'about_section_title': 'Our Mission',
      'about_section_p1': 'Quran Kareem is designed to be a beautiful and accessible tool for reading, listening to, and engaging with the Holy Quran. Our goal is to provide a seamless and enriching experience for Muslims around the world to connect with the word of Allah.',
      'about_section_p2': 'Whether you want to read surahs, listen to your favorite reciters, or explore the deeper meanings of the verses, this application provides a comprehensive suite of features to support your spiritual journey.',
      'Key Features': 'Key Features',
      'feature_0': 'Read and listen to all 114 Surahs.',
      'feature_1': 'Choose from a wide variety of renowned reciters.',
      'feature_2': 'Listen to live Quran radio stations from around the world.',
      'feature_3': 'Get AI-powered explanations for ayahs to deepen your understanding.',
      'feature_4': 'Find the Qibla direction with our accurate compass.',
      'feature_5': 'Check daily prayer times for your location.',
      'feature_6': 'Save your favorite surahs and ayahs for quick access.',
      'feature_7': 'Bookmark ayahs to easily return to them later.',
      'feature_8': 'Beautiful and easy-to-use interface with multi-language support (Arabic & English).',
      'Data Sources': 'Data Sources',
      'data_sources_intro': 'This application relies on several high-quality, public APIs to provide accurate and reliable data. We are grateful to the developers behind these services:',
      'quran_com_desc': 'Used for Surah lists, Ayah text, translations, and tafsir information.',
      'mp3quran_desc': 'Used for full-surah recitations and live radio station data.',
      'everyayah_desc': 'Provides the audio files for the per-ayah recitation feature.',
      'aladhan_desc': 'Used to fetch daily prayer times based on user location.',
      'gemini_desc': 'Powers the "Ask AI" feature for verse explanations.',
      'Developed By': 'Developed By',
      'developer_motto': 'Crafting meaningful digital experiences.',
      'Translation': 'Translation',
      'Translation Source': 'Translation Source',
      'None': 'None',
      'Settings': 'Settings',
      'Word by Word': 'Word by Word',
      'On': 'On',
      'Off': 'Off',
      
      // New Services Section
      'More': 'More',
      'Religious Services': 'Religious Services',
      'Useful Tools': 'Useful Tools',
      'Information': 'Information',
      
      // Digital Tasbih
      'Digital Tasbih': 'Digital Tasbih',
      'Tasbih': 'Tasbih',
      'Reset': 'Reset',
      'Total Count': 'Total Count',
      'Current Round': 'Current Round',
      'SubhanAllah': 'SubhanAllah',
      'Alhamdulillah': 'Alhamdulillah',
      'Allahu Akbar': 'Allahu Akbar',
      'La hawla wa la quwwata illa billah': 'La hawla wa la quwwata illa billah',
      'Astaghfirullah': 'Astaghfirullah',
      'La ilaha illa Allah': 'La ilaha illa Allah',
      'Current Count': 'Current Count',
      'All Tasbihat': 'All Tasbihat',
      '33 per round': '33 per round',
      'Choose Tasbih': 'Choose Tasbih',
      'Tap to count': 'Tap to count',
      'Reset Current': 'Reset Current',
      'Reset All': 'Reset All',
      'Spiritual Benefits': 'Spiritual Benefits',
      'Inner Peace and Tranquility': 'Inner Peace and Tranquility',
      'Spiritual Strength': 'Spiritual Strength',
      'Mindfulness and Focus': 'Mindfulness and Focus',
      'Divine Connection': 'Divine Connection',
      'Tap the circle to count your dhikr. Each complete round consists of 33 repetitions.': 'Tap the circle to count your dhikr. Each complete round consists of 33 repetitions.',
      
      // Adhkar
      'Adhkar': 'Adhkar',
      'Morning Adhkar': 'Morning Adhkar',
      'Evening Adhkar': 'Evening Adhkar',
      'Post-Prayer Adhkar': 'Post-Prayer Adhkar',
      'Sleeping Adhkar': 'Sleeping Adhkar',
      'times': 'times',
      'Read': 'Read',
      'Completed': 'Completed',
      'Mark as Read': 'Mark as Read',
      'Reset Category': 'Reset Category',
      'Benefits of Regular Dhikr': 'Benefits of Regular Dhikr',
      'Heart Purification': 'Heart Purification',
      'Divine Protection': 'Divine Protection',
      'Increased Barakah': 'Increased Barakah',
      'Peace of Mind': 'Peace of Mind',
      'Spiritual Elevation': 'Spiritual Elevation',
      'Community Blessing': 'Community Blessing',
      'Read each dhikr the specified number of times. Click the Read button after completing each recitation.': 'Read each dhikr the specified number of times. Click the Read button after completing each recitation.',
      
      // 99 Names of Allah
      '99 Names of Allah': '99 Names of Allah',
      'Asma ul Husna': 'Asma ul Husna',
      'The 99 Beautiful Names': 'The 99 Beautiful Names',
      'Allah Name': 'Name',
      'Meaning': 'Meaning',
      'Description': 'Description',
      'No names found matching your search.': 'No names found matching your search.',
      'Clear Search': 'Clear Search',
      'Benefits of Reciting Asma ul Husna': 'Benefits of Reciting Asma ul Husna',
      'Strengthens Faith': 'Strengthens Faith',
      'Brings Inner Peace': 'Brings Inner Peace',
      'Increases Knowledge': 'Increases Knowledge',
      'Click on any name to learn more about its meaning and significance.': 'Click on any name to learn more about its meaning and significance.',
      'Play Audio': 'Play Audio',
      
      // Hadith
      'Hadith': 'Hadith',
      'Sahih Bukhari': 'Sahih Bukhari',
      'Sahih Muslim': 'Sahih Muslim',
      'Sunan Abu Dawud': 'Sunan Abu Dawud',
      'Jami at-Tirmidhi': 'Jami at-Tirmidhi',
      'Narrator': 'Narrator',
      'Reference': 'Reference',
      
      // Zakat Calculator
      'Zakat Calculator': 'Zakat Calculator',
      'Calculate Zakat': 'Calculate Zakat',
      'Gold': 'Gold',
      'Silver': 'Silver',
      'Cash': 'Cash',
      'Savings': 'Savings',
      'Investment': 'Investment',
      'Amount': 'Amount',
      'Total Wealth': 'Total Wealth',
      'Zakat Amount': 'Zakat Amount',
      'Nisab Threshold': 'Nisab Threshold',
      'Currency': 'Currency',
      
      // Quran Reading Plan
      'Quran Reading Plan': 'Quran Reading Plan',
      'Complete in': 'Complete in',
      '30 days': '30 days',
      '60 days': '60 days',
      '90 days': '90 days',
      'Custom': 'Custom',
      'Start Date': 'Start Date',
      'End Date': 'End Date',
      'Daily Reading': 'Daily Reading',
      'Progress': 'Progress',
      'Days Completed': 'Days Completed',
      'Days Remaining': 'Days Remaining',
      
      // Islamic Calendar
      'Islamic Calendar': 'Islamic Calendar',
      'Hijri Date': 'Hijri Date',
      'Gregorian Date': 'Gregorian Date',
      'Current Month': 'Current Month',
      'Islamic Events': 'Islamic Events',
      'Muharram': 'Muharram',
      'Safar': 'Safar',
      'Rabi al-Awwal': 'Rabi al-Awwal',
      'Rabi al-Thani': 'Rabi al-Thani',
      'Jumada al-Awwal': 'Jumada al-Awwal',
      'Jumada al-Thani': 'Jumada al-Thani',
      'Rajab': 'Rajab',
      'Shaban': 'Shaban',
      'Ramadan': 'Ramadan',
      'Shawwal': 'Shawwal',
      'Dhul Qadah': 'Dhul Qadah',
      'Dhul Hijjah': 'Dhul Hijjah',
    },
  };

  language = signal<'ar' | 'en'>('ar');
  direction = computed(() => (this.language() === 'ar' ? 'rtl' : 'ltr'));

  constructor() {
    // Fix: Use effect to react to signal changes for side-effects like updating the DOM.
    effect(() => {
      document.documentElement.lang = this.language();
      document.documentElement.dir = this.direction();
    });
  }

  setLanguage(lang: 'ar' | 'en') {
    this.language.set(lang);
  }

  translate(key: string) {
    return computed(() => this.translations[this.language()][key] || key);
  }
}
